'------------------------------------------------------------------------------
' <auto-generated>
'     Este código se generó a partir de una plantilla.
'
'     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
'     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class cliente
    Public Property dnicli As Integer
    Public Property nomyape As String
    Public Property telefono As Integer
    Public Property direccion As String
    Public Property mail As String
    Public Property estado As String

    Public Overridable Property ventaCabecera As ICollection(Of ventaCabecera) = New HashSet(Of ventaCabecera)

End Class
