'------------------------------------------------------------------------------
' <auto-generated>
'     Este código se generó a partir de una plantilla.
'
'     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
'     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class libro
    Public Property isbn As Long
    Public Property titulo As String
    Public Property idautor As Integer
    Public Property idgenero As Integer
    Public Property ideditorial As Integer
    Public Property sinopsis As String
    Public Property precio As Decimal
    Public Property stockmin As Integer
    Public Property stock As Integer
    Public Property anoedicion As Integer
    Public Property portada As Byte()

    Public Overridable Property autor As autor
    Public Overridable Property editorial As editorial
    Public Overridable Property genero As genero
    Public Overridable Property ventadetalle As ICollection(Of ventadetalle) = New HashSet(Of ventadetalle)

End Class
