'------------------------------------------------------------------------------
' <auto-generated>
'     Este código se generó a partir de una plantilla.
'
'     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
'     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Data.Entity
Imports System.Data.Entity.Infrastructure

Partial Public Class Database1Entities
    Inherits DbContext

    Public Sub New()
        MyBase.New("name=Database1Entities")
    End Sub

    Protected Overrides Sub OnModelCreating(modelBuilder As DbModelBuilder)
        Throw New UnintentionalCodeFirstException()
    End Sub

    Public Overridable Property autor() As DbSet(Of autor)
    Public Overridable Property cliente() As DbSet(Of cliente)
    Public Overridable Property editorial() As DbSet(Of editorial)
    Public Overridable Property genero() As DbSet(Of genero)
    Public Overridable Property libro() As DbSet(Of libro)
    Public Overridable Property Usuario() As DbSet(Of Usuario)
    Public Overridable Property ventaCabecera() As DbSet(Of ventaCabecera)
    Public Overridable Property ventadetalle() As DbSet(Of ventadetalle)

End Class
