'------------------------------------------------------------------------------
' <auto-generated>
'     Este código se generó a partir de una plantilla.
'
'     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
'     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class Usuario
    Public Property dni As Integer
    Public Property nombre As String
    Public Property apellido As String
    Public Property username As String
    Public Property pass As String
    Public Property foto As Byte()
    Public Property tipousuario As String
    Public Property estado As String

    Public Overridable Property ventaCabecera As ICollection(Of ventaCabecera) = New HashSet(Of ventaCabecera)

End Class
