'------------------------------------------------------------------------------
' <auto-generated>
'     Este código se generó a partir de una plantilla.
'
'     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
'     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class ventacabecera
    Public Property idventa As Integer
    Public Property dnicli As Integer
    Public Property tipopago As String
    Public Property subtotal As Decimal
    Public Property descuento As Decimal
    Public Property total As Decimal
    Public Property dni As Nullable(Of Integer)

    Public Overridable Property cliente As cliente
    Public Overridable Property usuario As usuario
    Public Overridable Property ventadetalle As ICollection(Of ventadetalle) = New HashSet(Of ventadetalle)

End Class
