'------------------------------------------------------------------------------
' <auto-generated>
'     Este código se generó a partir de una plantilla.
'
'     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
'     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class ventadetalle
    Public Property Idventa As Integer
    Public Property isbn As Nullable(Of Integer)
    Public Property cant As Nullable(Of Integer)
    Public Property precio As Nullable(Of Double)
    Public Property importe As Nullable(Of Double)

    Public Overridable Property libro As libro
    Public Overridable Property ventaCabecera As ventaCabecera

End Class
