'------------------------------------------------------------------------------
' <auto-generated>
'     Este código se generó a partir de una plantilla.
'
'     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
'     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class ventaCabecera
    Public Property Idventa As Integer
    Public Property dnicli As Integer
    Public Property dni As Integer
    Public Property tipopago As String
    Public Property subtotal As Double
    Public Property descuento As Double
    Public Property total As Double
    Public Property fechaventa As Date

    Public Overridable Property cliente As cliente
    Public Overridable Property ventadetalle As ICollection(Of ventadetalle) = New HashSet(Of ventadetalle)
    Public Overridable Property Usuario As Usuario

End Class
